apiVersion: v1
kind: Service
metadata:
  name: greenguard
spec:
  ports:
  - name: jupyter
    port: 8888
    nodePort: 30088
  selector:
    app: greenguard
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenguard
spec:
  selector:
    matchLabels:
      app: greenguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: greenguard
    spec:
      containers:
      - image: signalsdev/greenguard:0.2.2.dev0
        name: greenguard
        ports:
        - containerPort: 8888
          name: jupyter
